# Generated by Django 5.2 on 2026-06-19 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('university', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('photo', models.URLField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('mentor', models.CharField(default='Lead Mentor', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('not_started', 'Not Started')], default='not_started', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='interns.intern')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
                ('mon', models.CharField(blank=True, default='', max_length=10)),
                ('tue', models.CharField(blank=True, default='', max_length=10)),
                ('wed', models.CharField(blank=True, default='', max_length=10)),
                ('thu', models.CharField(blank=True, default='', max_length=10)),
                ('fri', models.CharField(blank=True, default='', max_length=10)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to='interns.intern')),
            ],
        ),
    ]
