# Generated by Django 6.0.6 on 2026-06-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='attendance_rate',
            field=models.PositiveSmallIntegerField(default=100, help_text='Tỷ lệ điểm danh (%), mentor tự nhập, 0-100'),
        ),
        migrations.AddField(
            model_name='intern',
            name='skill_growth',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Điểm đánh giá kỹ năng, thang 0.0 - 10.0', max_digits=3),
        ),
        migrations.AddField(
            model_name='intern',
            name='skill_growth_delta',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Chênh lệch so với lần đánh giá trước, vd +1.2 hoặc -0.5', max_digits=3),
        ),
        migrations.AlterField(
            model_name='intern',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
