# Generated by Django 5.2 on 2026-06-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_intern_attendance_rate_intern_skill_growth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='week',
            field=models.CharField(default='Week 1: June 22 - June 28', max_length=50),
        ),
    ]
